var VALID_SYLLOGISMS = {
  1: ['AAA', 'EAE', 'AII', 'EIO', 'AAI', 'EAO'],
  2: ['EAE', 'AEE', 'EIO', 'AOO', 'EAO', 'AEO'],
  3: ['AAI', 'IAI', 'AII', 'EAO', 'OAO', 'EIO'],
  4: ['AAI', 'AEE', 'IAI', 'EAO', 'EIO', 'AEO'],
};

var SYLLOGISM_NAMES = {
  'AAA': 'Barbara', 'EAE': 'Celarent', 'AII': 'Darii', 'EIO': 'Ferio',
  'AAI': 'Barbari', 'EAO': 'Celaront', 'AEE': 'Camestres', 'AOO': 'Baroco',
  'AEO': 'Camestros', 'IAI': 'Disamis', 'OAO': 'Bocardo',
};

var MNEMONICS = {
  '1-AAA': 'bArbArA', '1-EAE': 'cElArEnt', '1-AII': 'dArII', '1-EIO': 'fErIO',
  '1-AAI': 'bArbArI', '1-EAO': 'cElArOnt', '2-EAE': 'cEsArE', '2-AEE': 'cAmEstrEs',
  '2-EIO': 'fEstInO', '2-AOO': 'bArOcO', '2-EAO': 'cEsArO', '2-AEO': 'cAmEstrOs',
  '3-AAI': 'dArAptI', '3-IAI': 'dIsAmIs', '3-AII': 'dAtIsI', '3-EAO': 'fElAptOn',
  '3-OAO': 'bOcArdO', '3-EIO': 'fErIsOn', '4-AAI': 'brAmAntIp', '4-AEE': 'cAmEnEs',
  '4-IAI': 'dImArIs', '4-EAO': 'fEsApO', '4-EIO': 'frEsIsOn', '4-AEO': 'cAmEnOs',
};

var SyllogismsStandard = [
  { "figure": 1, "mood": "AAA", "terms": { "majorTerm": "mortal", "minorTerm": "humans", "middleTerm": "animals" } },
  { "figure": 1, "mood": "EAE", "terms": { "majorTerm": "have fur", "minorTerm": "snakes", "middleTerm": "reptiles" } },
  { "figure": 1, "mood": "AII", "terms": { "majorTerm": "playful", "minorTerm": "pets", "middleTerm": "kittens" } },
  { "figure": 1, "mood": "EIO", "terms": { "majorTerm": "fun", "minorTerm": "readings", "middleTerm": "homework" } },
  { "figure": 1, "mood": "AAI", "terms": { "majorTerm": "mortal", "minorTerm": "humans", "middleTerm": "animals" } },
  { "figure": 1, "mood": "EAO", "terms": { "majorTerm": "have fur", "minorTerm": "snakes", "middleTerm": "reptiles" } },
  { "figure": 2, "mood": "EAE", "terms": { "majorTerm": "healthy food", "minorTerm": "cakes", "middleTerm": "gain weight" } },
  { "figure": 2, "mood": "AEE", "terms": { "majorTerm": "horse", "minorTerm": "humans", "middleTerm": "have bloating" } },
  { "figure": 2, "mood": "EIO", "terms": { "majorTerm": "lazy", "minorTerm": "students", "middleTerm": "pass exams" } },
  { "figure": 2, "mood": "AOO", "terms": { "majorTerm": "informative", "minorTerm": "websites", "middleTerm": "useful" } },
  { "figure": 2, "mood": "EAO", "terms": { "majorTerm": "healthy food", "minorTerm": "cakes", "middleTerm": "gain weight" } },
  { "figure": 2, "mood": "AEO", "terms": { "majorTerm": "horse", "minorTerm": "humans", "middleTerm": "have bloating" } },
  { "figure": 3, "mood": "AAI", "terms": { "majorTerm": "nutritious", "minorTerm": "tasty things", "middleTerm": "fruits" } },
  { "figure": 3, "mood": "IAI", "terms": { "majorTerm": "beautiful", "minorTerm": "useful things", "middleTerm": "cups" } },
  { "figure": 3, "mood": "AII", "terms": { "majorTerm": "red", "minorTerm": "boarding students", "middleTerm": "diligent boys" } },
  { "figure": 3, "mood": "EAO", "terms": { "majorTerm": "new", "minorTerm": "cracked things", "middleTerm": "pitchers" } },
  { "figure": 3, "mood": "OAO", "terms": { "majorTerm": "have tails", "minorTerm": "mammals", "middleTerm": "cats" } },
  { "figure": 3, "mood": "EIO", "terms": { "majorTerm": "edible", "minorTerm": "green things", "middleTerm": "trees" } },
  { "figure": 4, "mood": "AAI", "terms": { "majorTerm": "apples", "minorTerm": "ripe fruits", "middleTerm": "useful" } },
  { "figure": 4, "mood": "AEE", "terms": { "majorTerm": "bright", "minorTerm": "indoor flowers", "middleTerm": "fragrant" } },
  { "figure": 4, "mood": "IAI", "terms": { "majorTerm": "small", "minorTerm": "colorful birds", "middleTerm": "eat honey" } },
  { "figure": 4, "mood": "EAO", "terms": { "majorTerm": "humans", "minorTerm": "mythical beings", "middleTerm": "perfect" } },
  { "figure": 4, "mood": "EIO", "terms": { "majorTerm": "competent", "minorTerm": "workers", "middleTerm": "make mistakes" } },
  { "figure": 4, "mood": "AEO", "terms": { "majorTerm": "bright", "minorTerm": "indoor flowers", "middleTerm": "fragrant" } }
];

var SyllogismAnswers = {
  "1-AAA": { "dd": "DD=9-0,10-0,11-1,12-0,13--,14-0,15--,16--", "md": "MD=5-1,6-0,7--,8--" },
  "1-EAE": { "dd": "DD=9-0,10-0,11-0,12-1,13-0,14--,15-1,16--", "md": "MD=5-0,6-1,7-1,8--" },
  "1-AII": { "dd": "DD=9--,10--,11-1,12-0,13--,14-0,15--,16--", "md": "MD=5-1,6--,7--,8--" },
  "1-EIO": { "dd": "DD=9--,10--,11-0,12-1,13-0,14--,15--,16--", "md": "MD=5--,6-1,7--,8--" },
  "1-AAI": { "dd": "DD=9-0,10-0,11-1,12-0,13--,14-0,15--,16--", "md": "MD=5-1,6-0,7--,8--" },
  "1-EAO": { "dd": "DD=9-0,10-0,11-0,12-1,13-0,14--,15-1,16--", "md": "MD=5-0,6-1,7-1,8--" },
  "2-EAE": { "dd": "DD=9-0,10-0,11-0,12-1,13-0,14--,15-1,16--", "md": "MD=5-0,6-1,7-1,8--" },
  "2-AEE": { "dd": "DD=9-0,10-1,11-0,12-0,13-1,14--,15-0,16--", "md": "MD=5-0,6-1,7-1,8--" },
  "2-EIO": { "dd": "DD=9--,10--,11-0,12-1,13-0,14--,15--,16--", "md": "MD=5--,6-1,7--,8--" },
  "2-AOO": { "dd": "DD=9-0,10-1,11--,12--,13--,14--,15-0,16--", "md": "MD=5--,6-1,7--,8--" },
  "2-EAO": { "dd": "DD=9-0,10-0,11-0,12-1,13-0,14--,15-1,16--", "md": "MD=5-0,6-1,7-1,8--" },
  "2-AEO": { "dd": "DD=9-0,10-1,11-0,12-0,13-1,14--,15-0,16--", "md": "MD=5-0,6-1,7-1,8--" },
  "3-AAI": { "dd": "DD=9--,10--,11-1,12-0,13-0,14-0,15--,16--", "md": "MD=5-1,6--,7--,8--" },
  "3-IAI": { "dd": "DD=9--,10--,11-1,12--,13-0,14-0,15--,16--", "md": "MD=5-1,6--,7--,8--" },
  "3-AII": { "dd": "DD=9--,10--,11-1,12-0,13--,14-0,15--,16--", "md": "MD=5-1,6--,7--,8--" },
  "3-EAO": { "dd": "DD=9--,10--,11-0,12-1,13-0,14-0,15--,16--", "md": "MD=5--,6-1,7--,8--" },
  "3-OAO": { "dd": "DD=9--,10--,11--,12-1,13-0,14-0,15--,16--", "md": "MD=5--,6-1,7--,8--" },
  "3-EIO": { "dd": "DD=9--,10--,11-0,12-1,13-0,14--,15--,16--", "md": "MD=5--,6-1,7--,8--" },
  "4-AAI": { "dd": "DD=9-0,10--,11-1,12--,13-0,14-0,15-0,16--", "md": "MD=5-1,6--,7-0,8--" },
  "4-AEE": { "dd": "DD=9-0,10-1,11-0,12-0,13-1,14--,15-0,16--", "md": "MD=5-0,6-1,7-1,8--" },
  "4-IAI": { "dd": "DD=9--,10--,11-1,12--,13-0,14-0,15--,16--", "md": "MD=5-1,6--,7--,8--" },
  "4-EAO": { "dd": "DD=9--,10--,11-0,12-1,13-0,14-0,15--,16--", "md": "MD=5--,6-1,7--,8--" },
  "4-EIO": { "dd": "DD=9--,10--,11-0,12-1,13-0,14--,15--,16--", "md": "MD=5--,6-1,7--,8--" },
  "4-AEO": { "dd": "DD=9-0,10-1,11-0,12-0,13-1,14--,15-0,16--", "md": "MD=5-0,6-1,7-1,8--" }
};

var en = {
  'nav.syllogisms': 'Atlas',
  'nav.learn': 'Logic School',
  'footer.copyright': '\u00a9 {year} Lewis Carroll Logic Game.',
  'home.code': 'Code:',
  'home.clear_board': 'Clear Board',
  'home.controls': 'Controls',
  'home.large_diagram': 'Large Diagram (Premises)',
  'home.small_diagram': 'Small Diagram (Conclusions)',
  'home.copy': 'Copy',
  'home.copied': 'Copied!',
  'home.copy_prefix': 'Is the following syllogism solved correctly:',
  'home.terms_label': 'Terms:',
  'home.solution_label': 'Solution:',
  'quiz.major_premise': 'Major Premise',
  'quiz.minor_premise': 'Minor Premise',
  'quiz.conclusion': 'Conclusion',
  'quiz.minor_term': 'Minor (S)',
  'quiz.major_term': 'Major (P)',
  'quiz.middle_term': 'Middle (M)',
  'quiz.check_answer': 'Check Answer',
  'quiz.next': 'Next Syllogism \u2192',
  'quiz.correct': 'Correct!',
  'quiz.not_correct': 'Not quite right',
  'quiz.show_answer': 'Show Answer',
  'quiz.close': 'Close',
  'quiz.are': 'are',
  'quiz.have': 'have',
  'quiz.all_word': 'All',
  'quiz.no_word': 'No',
  'quiz.some_word': 'Some',
  'quiz.not_word': 'not',
  'quiz.help_title': 'Logic Rules',
  'quiz.help_visual_guide': 'Visual Guide',
  'quiz.help_large_desc': 'Large Diagram (Premises) - 16 cells.',
  'quiz.help_small_desc': 'Small Diagram (Conclusions) - 8 cells.',
  'quiz.help_symbols_title': 'Logical Symbols',
  'quiz.help_symbol_subset': '\u2286 : Is a subset of',
  'quiz.help_symbol_intersection': '\u2229 : Intersection',
  'quiz.help_symbol_not_empty': '\u2260 \u2205 : Is not empty',
  'quiz.help_symbol_complement': "' : Complement",
  'quiz.help_col1': 'Proposition',
  'quiz.help_col2': 'Rule',
  'quiz.help_col3': 'Action',
  'quiz.help_col4': 'Cells',
  'quiz.help_close': 'Close Reference',
  'quiz.help_method_title': "Carroll's Method",
  'quiz.help_method_intro': "Lewis Carroll's method of solving syllogisms using diagrams is highly visual and mathematically rigorous.",
  'quiz.help_method_rule1_title': '1. Elimination Rule',
  'quiz.help_method_rule1_desc': 'This rule is used to eliminate the middle term (m).\n\nIf an area is empty (Zero): If a certain sector in the Large Diagram is cleared with zeros on both the m and m\' sides, that zero is directly transferred to the Small Diagram.\n\nIf an area has a unit: If the middle term m is completely enclosed by zeros in three cells, any object is pushed out to the only remaining free cell.',
  'quiz.help_method_rule2_title': '2. Existence (Unit Finding) Rule',
  'quiz.help_method_rule2_desc': "If the premises fill three out of four cells of a sector with zeros (0), a unit (1) must be written into the fourth remaining free cell.\n\nA class cannot simply vanish, so the zeros push the unit into the last safe place.",
  'quiz.help_method_rule3_title': '3. "Sitting on the Fence" Rule',
  'quiz.help_method_rule3_desc': 'This rule applies when we have particular premises.\n\nIf a premise says "Some x are m" but we don\'t know whether they are y or y\', the unit is placed on the line dividing those two cells.',
  'quiz.help_method_rule4_title': '4. Transfer to Small Diagram Rules',
  'quiz.help_method_rule4_desc': 'Once the Large Diagram is filled, its data is transferred to the Small Diagram.\n\nZero transfer: For an SD cell to get a zero (0), both corresponding LD cells in that sector must be zeros.\n\nUnit transfer: For an SD cell to get a unit (1), at least one of the two corresponding LD cells must have a unit.',
  'quiz.help_method_summary_title': 'Summary: How to Read the Conclusion',
  'quiz.help_method_summary_desc': 'If cell 6 (y\') is 0 and cell 5 (y) is 1 \u2192 All x are y.\n\nIf cell 5 (y) is 0 and cell 6 (y\') is 1 \u2192 No x are y.\n\nIf a cell simply has a 1 (and the other is empty) \u2192 Some x are y (or not-y).',
  'quiz.help_row1_1': 'All m are x',
  'quiz.help_row1_2': 'Pushing Up',
  'quiz.help_row1_3': 'Clear m bottom',
  'quiz.help_row1_4': '13, 14',
  'quiz.help_row2_1': 'All m are not-x',
  'quiz.help_row2_2': 'Pushing Down',
  'quiz.help_row2_3': 'Clear m top',
  'quiz.help_row2_4': '11, 12',
  'quiz.help_row3_1': 'No m is x',
  'quiz.help_row3_2': 'Locking (m and x)',
  'quiz.help_row3_3': 'Clear intersection',
  'quiz.help_row3_4': '11, 12',
  'quiz.help_row4_1': 'All x are m',
  'quiz.help_row4_2': 'Pushing Inward',
  'quiz.help_row4_3': 'Clear x outward',
  'quiz.help_row4_4': '9, 10',
  'quiz.help_row5_1': 'All y are m',
  'quiz.help_row5_2': 'Pushing Inward (Side)',
  'quiz.help_row5_3': 'Clear y outward',
  'quiz.help_row5_4': '9, 15',
  'quiz.help_row6_1': 'All m are y',
  'quiz.help_row6_2': 'Pushing Left',
  'quiz.help_row6_3': 'Clear m right',
  'quiz.help_row6_4': '12, 14',
  'quiz.help_row7_1': 'No y is m',
  'quiz.help_row7_2': 'Locking (Side)',
  'quiz.help_row7_3': 'Clear intersection',
  'quiz.help_row7_4': '11, 13',
  'atlas.title': 'Syllogism Atlas',
  'atlas.subtitle': 'A comprehensive collection of the 24 standard valid syllogisms.',
  'atlas.search_placeholder': 'Search by mood or mnemonic...',
  'atlas.figure': 'Figure',
  'atlas.syllogisms_count': '{count} SYLLOGISMS',
  'atlas.table.mood': 'Mood',
  'atlas.table.mnemonic': 'Mnemonic',
  'atlas.no_results': 'No syllogisms match your search in this figure.',
  'atlas.footer.label': 'Encyclopedic Data',
  'atlas.footer.quote': '"The logic of the world is prior to all truth and falsehood."',
  'atlas.footer.total_valid': 'Total Valid',
  'atlas.footer.logical_figures': 'Logical Figures',
  'atlas.footer.moods_per_figure': 'Moods / Figure',
  'mortal': 'mortal', 'humans': 'humans', 'animals': 'animals', 'have fur': 'have fur',
  'snakes': 'snakes', 'reptiles': 'reptiles', 'playful': 'playful', 'pets': 'pets',
  'kittens': 'kittens', 'fun': 'fun', 'readings': 'readings', 'homework': 'homework',
  'healthy food': 'healthy food', 'cakes': 'cakes', 'gain weight': 'gain weight',
  'horse': 'horse', 'have bloating': 'have bloating', 'lazy': 'lazy',
  'students': 'students', 'pass exams': 'pass exams', 'informative': 'informative',
  'websites': 'websites', 'useful': 'useful', 'nutritious': 'nutritious',
  'tasty things': 'tasty things', 'fruits': 'fruits', 'beautiful': 'beautiful',
  'useful things': 'useful things', 'cups': 'cups', 'red': 'red',
  'boarding students': 'boarding students', 'diligent boys': 'diligent boys',
  'new': 'new', 'cracked things': 'cracked things', 'pitchers': 'pitchers',
  'have tails': 'have tails', 'mammals': 'mammals', 'cats': 'cats',
  'edible': 'edible', 'green things': 'green things', 'trees': 'trees',
  'apples': 'apples', 'ripe fruits': 'ripe fruits', 'bright': 'bright',
  'indoor flowers': 'indoor flowers', 'fragrant': 'fragrant', 'small': 'small',
  'colorful birds': 'colorful birds', 'eat honey': 'eat honey',
  'mythical beings': 'mythical beings', 'perfect': 'perfect',
  'competent': 'competent', 'workers': 'workers', 'make mistakes': 'make mistakes',
};

var lt = {
  'nav.syllogisms': 'Atlasas',
  'nav.learn': 'Logikos mokykla',
  'footer.copyright': '\u00a9 {year} Lewis Carroll logikos \u017eaidimas.',
  'home.code': 'Kodas:',
  'home.clear_board': 'I\u0161valyti visk\u0105',
  'home.controls': 'Valdymas',
  'home.large_diagram': 'Did\u017eioji diagrama',
  'home.small_diagram': 'Ma\u017eoji diagrama',
  'home.copy': 'Kopijuoti',
  'home.copied': 'Nukopijuota!',
  'quiz.major_premise': 'Didesn\u0117 prielaida',
  'quiz.minor_premise': 'Ma\u017eesn\u0117 prielaida',
  'quiz.conclusion': 'I\u0161vada',
  'quiz.check_answer': 'Tikrinti atsakym\u0105',
  'quiz.close': 'U\u017edaryti',
  'quiz.correct': 'Teisingai!',
  'quiz.not_correct': 'Ne visai teisingai',
  'atlas.title': 'Silogizm\u0173 atlasas',
  'atlas.subtitle': 'I\u0161samus 24 standartini\u0173 galiojan\u010di\u0173 silogizm\u0173 rinkinys.',
  'atlas.search_placeholder': 'Ie\u0161kokite pagal modalum\u0105 arba mnemonik\u0105...',
  'atlas.table.mood': 'Modalumas',
  'atlas.table.mnemonic': 'Mnemonika',
  'atlas.footer.label': 'Enciklopediniai Duomenys',
  'atlas.footer.quote': '"Pasaulio logika yra prie\u0161 bet koki\u0105 ties\u0105 ir mel\u0105."',
  'atlas.footer.total_valid': 'I\u0161 viso galioja',
  'atlas.footer.logical_figures': 'Login\u0117s fig\u016bros',
  'atlas.footer.moods_per_figure': 'Modalumai / Fig\u016broje',
  'atlas.figure': 'Fig\u016bra',
  'quiz.help_title': 'Logikos taisykl\u0117s',
  'quiz.help_visual_guide': 'Vizualus Gidas',
  'quiz.help_large_desc': 'Did\u017eioji Diagrama (Prielaidos) - 16 langeli\u0173.',
  'quiz.help_small_desc': 'Ma\u017eoji Diagrama (I\u0161vados) - 8 langeliai.',
  'quiz.help_symbols_title': 'Loginiai Simboliai',
  'quiz.help_symbol_subset': '\u2286 : Yra poaibis (Visi A yra B)',
  'quiz.help_symbol_intersection': '\u2229 : Sankirta (A IR B persidengia)',
  'quiz.help_symbol_not_empty': '\u2260 \u2205 : N\u0117ra tu\u0161\u010dia aib\u0117 (Egzistuoja)',
  'quiz.help_symbol_complement': "' : Papildinys (NE terminas, pvz. x')",
  'quiz.help_col1': 'Teiginys',
  'quiz.help_col2': 'Taisykl\u0117',
  'quiz.help_col3': 'Veiksmas',
  'quiz.help_col4': 'Langeliai',
  'quiz.help_row1_1': 'Visi m yra x',
  'quiz.help_row1_2': 'St\u016bmimas Auk\u0161tyn',
  'quiz.help_row1_3': 'I\u0161valyti m apa\u010di\u0105',
  'quiz.help_row1_4': '13, 14',
  'quiz.help_row2_1': 'Visi m n\u0117ra x',
  'quiz.help_row2_2': 'St\u016bmimas \u017demyn',
  'quiz.help_row2_3': 'I\u0161valyti m vir\u0161\u0173',
  'quiz.help_row2_4': '11, 12',
  'quiz.help_row3_1': 'Joks m n\u0117ra x',
  'quiz.help_row3_2': 'U\u017erakinimas (m ir x)',
  'quiz.help_row3_3': 'I\u0161valyti sankirt\u0105',
  'quiz.help_row3_4': '11, 12',
  'quiz.help_row4_1': 'Visi x yra m',
  'quiz.help_row4_2': 'St\u016bmimas \u012e Vid\u0173',
  'quiz.help_row4_3': 'I\u0161valyti x \u012f i\u0161or\u0119',
  'quiz.help_row4_4': '9, 10',
  'quiz.help_row5_1': 'Visi y yra m',
  'quiz.help_row5_2': 'St\u016bmimas \u012e Vid\u0173 (\u0160onas)',
  'quiz.help_row5_3': 'I\u0161valyti y \u012f i\u0161or\u0119',
  'quiz.help_row5_4': '9, 15',
  'quiz.help_row6_1': 'Visi m yra y',
  'quiz.help_row6_2': 'St\u016bmimas \u012e Kair\u0119',
  'quiz.help_row6_3': 'I\u0161valyti m de\u0161in\u0119',
  'quiz.help_row6_4': '12, 14',
  'quiz.help_row7_1': 'Joks y n\u0117ra m',
  'quiz.help_row7_2': 'U\u017erakinimas (\u0160onas)',
  'quiz.help_row7_3': 'I\u0161valyti sankirt\u0105',
  'quiz.help_row7_4': '11, 13',
  'quiz.help_close': 'U\u017edaryti \u017dinyn\u0105',
  'quiz.help_method_title': 'Carrollio metodas',
  'quiz.help_method_intro': 'Lewiso Carrollio silogizm\u0173 sprendimo metodas, naudojantis diagramas, yra labai vaizdingas ir matemati\u0161kai grie\u017etas.',
  'quiz.help_method_rule1_title': '1. \u201eI\u0161st\u016bmimo\u201c taisykl\u0117 (Elimination)',
  'quiz.help_method_rule1_desc': '\u0160i taisykl\u0117 naudojama norint atsikratyti vidurinio termino (m).\n\nJei plotas tu\u0161\u010dias (Nulis): Jei tam tikras sektorius Did\u017eiojoje diagramoje abiejuose m ir m\' pusel\u0117se yra i\u0161valytas nuliais, tas nulis tiesiogiai perkeliamas \u012f Ma\u017e\u0105j\u0105 diagram\u0105.\n\nJei plotas turi vienet\u0105: Jei vidurinis terminas m yra visi\u0161kai u\u017edaromas nuliais trijuose langeliuose, vienetas yra i\u0161stumiamas \u012f vienintel\u012f likus\u012f laisv\u0105 langel\u012f.',
  'quiz.help_method_rule2_title': '2. \u201eVieneto suradimo\u201c (Egzistavimo) taisykl\u0117',
  'quiz.help_method_rule2_desc': 'Jei prielaidos nuliais (0) u\u017epildo tris i\u0161 keturi\u0173 sektoriaus langeli\u0173, vienetas (1) privalomai \u012fra\u0161omas \u012f ketvirt\u0105j\u012f, likus\u012f laisv\u0105 langel\u012f.\n\nKlas\u0117 negali tiesiog i\u0161nykti, tod\u0117l nuliai i\u0161stumia vienet\u0105 \u012f paskutin\u0119 saugi\u0105 viet\u0105.',
  'quiz.help_method_rule3_title': '3. \u201eS\u0117d\u0117jimo ant tvoros\u201c taisykl\u0117',
  'quiz.help_method_rule3_desc': '\u0160i taisykl\u0117 taikoma, kai turime dalines prielaidas.\n\nJei prielaida sako \u201eKai kurie x yra m\u201c, bet mes tiksliai ne\u017einome, ar jie yra y, ar y\', vienetas yra padedamas ant linijos, skirian\u010dios tuos du langelius.',
  'quiz.help_method_rule4_title': '4. Perk\u0117limo \u012f Ma\u017e\u0105j\u0105 diagram\u0105 (MD) taisykl\u0117s',
  'quiz.help_method_rule4_desc': 'Kai u\u017epildome Did\u017ei\u0105j\u0105 diagram\u0105, jos duomenys perkeliami \u012f Ma\u017e\u0105j\u0105 diagram\u0105.\n\nNulio perk\u0117limas: Kad MD langelis gaut\u0173 nul\u012f, abu atitinkami DD langeliai tame sektoriuje privalo b\u016bti nuliai.\n\nVieneto perk\u0117limas: Kad MD langelis gaut\u0173 vienet\u0105, pakanka, kad bent vienas i\u0161 dviej\u0173 atitinkam\u0173 DD langeli\u0173 tur\u0117t\u0173 vienet\u0105.',
  'quiz.help_method_summary_title': 'Apibendrinimas: Kaip skaitoma i\u0161vada i\u0161 MD?',
  'quiz.help_method_summary_desc': 'Jei langelis 6 (y\') yra 0, o langelis 5 (y) yra 1 \u2192 Visi x yra y.\n\nJei langelis 5 (y) yra 0, o langelis 6 (y\') yra 1 \u2192 N\u0117 vienas x n\u0117ra y.\n\nJei langelyje yra 1 (o kitas tu\u0161\u010dias) \u2192 Kai kurie x yra y (arba ne-y).',
  'mortal': 'mirtingi', 'humans': '\u017emon\u0117s', 'animals': 'gyv\u016bnai',
  'have fur': 'kailiniai', 'snakes': 'gyvat\u0117s', 'reptiles': 'ropliai',
  'playful': '\u017eaismingi', 'pets': 'augintiniai', 'kittens': 'ka\u010diukai',
  'fun': 'smag\u016bs', 'readings': 'skaitiniai', 'homework': 'nam\u0173 darbai',
  'healthy food': 'sveikas maistas', 'cakes': 'pyragai', 'gain weight': 'storinantys',
  'horse': 'arklys', 'have bloating': 'tinstantys', 'lazy': 'tinginiai',
  'students': 'studentai', 'pass exams': 'i\u0161laiko egzaminus',
  'informative': 'informatyv\u016bs', 'websites': 'svetain\u0117s', 'useful': 'naudingi',
  'nutritious': 'maistingi', 'tasty things': 'skan\u016bs dalykai', 'fruits': 'vaisiai',
  'beautiful': 'gra\u017e\u016bs', 'useful things': 'naudingi daiktai', 'cups': 'puodeliai',
  'red': 'raudoni', 'boarding students': 'internato mokiniai', 'diligent boys': 'darb\u016bt\u016bs berniukai',
  'new': 'nauji', 'cracked things': '\u012ftr\u016bk\u0119 daiktai', 'pitchers': '\u0105so\u010diai',
  'have tails': 'turi uodegas', 'mammals': '\u017einduoliai', 'cats': 'kat\u0117s',
  'edible': 'valgomi', 'green things': '\u017eali daiktai', 'trees': 'med\u017eiai',
  'apples': 'obuoliai', 'ripe fruits': 'sunok\u0119 vaisiai', 'bright': 'ry\u0161k\u016bs',
  'indoor flowers': 'kambarin\u0117s g\u0117l\u0117s', 'fragrant': 'kvepiantys', 'small': 'ma\u017ei',
  'colorful birds': 'spalvoti pauk\u0161\u010diai', 'eat honey': 'valgo med\u0173',
  'mythical beings': 'mitin\u0117s b\u016btyb\u0117s', 'perfect': 'tobuli',
  'competent': 'kompetentingi', 'workers': 'darbuotojai', 'make mistakes': 'daro klaidas',
};

var Translations = { en: en, lt: lt };
var Languages = ['en', 'lt'];
