/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as SyllogismsRouteImport } from './routes/syllogisms'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as GameRouteImport } from './routes/game'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as Atlas3dRouteImport } from './routes/atlas3d'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllogismsRoute = SyllogismsRouteImport.update({
  id: '/syllogisms',
  path: '/syllogisms',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const Atlas3dRoute = Atlas3dRouteImport.update({
  id: '/atlas3d',
  path: '/atlas3d',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas3d': typeof Atlas3dRoute
  '/campaign': typeof CampaignRoute
  '/game': typeof GameRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/syllogisms': typeof SyllogismsRoute
  '/workshop': typeof WorkshopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas3d': typeof Atlas3dRoute
  '/campaign': typeof CampaignRoute
  '/game': typeof GameRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/syllogisms': typeof SyllogismsRoute
  '/workshop': typeof WorkshopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas3d': typeof Atlas3dRoute
  '/campaign': typeof CampaignRoute
  '/game': typeof GameRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/syllogisms': typeof SyllogismsRoute
  '/workshop': typeof WorkshopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/atlas3d'
    | '/campaign'
    | '/game'
    | '/learn'
    | '/practice'
    | '/syllogisms'
    | '/workshop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/atlas3d'
    | '/campaign'
    | '/game'
    | '/learn'
    | '/practice'
    | '/syllogisms'
    | '/workshop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/atlas3d'
    | '/campaign'
    | '/game'
    | '/learn'
    | '/practice'
    | '/syllogisms'
    | '/workshop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  Atlas3dRoute: typeof Atlas3dRoute
  CampaignRoute: typeof CampaignRoute
  GameRoute: typeof GameRoute
  LearnRoute: typeof LearnRoute
  PracticeRoute: typeof PracticeRoute
  SyllogismsRoute: typeof SyllogismsRoute
  WorkshopRoute: typeof WorkshopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllogisms': {
      id: '/syllogisms'
      path: '/syllogisms'
      fullPath: '/syllogisms'
      preLoaderRoute: typeof SyllogismsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas3d': {
      id: '/atlas3d'
      path: '/atlas3d'
      fullPath: '/atlas3d'
      preLoaderRoute: typeof Atlas3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  Atlas3dRoute: Atlas3dRoute,
  CampaignRoute: CampaignRoute,
  GameRoute: GameRoute,
  LearnRoute: LearnRoute,
  PracticeRoute: PracticeRoute,
  SyllogismsRoute: SyllogismsRoute,
  WorkshopRoute: WorkshopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
